// SynchronizedDictionary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

struct SynchronizedDictionary<K: Hashable, V>: @unchecked Sendable {
    private var dictionary = [K: V]()
    private let lock = NSRecursiveLock()

    subscript(key: K) -> V? {
        get {
            lock.withLock {
                dictionary[key]
            }
        }
        set {
            lock.withLock {
                dictionary[key] = newValue
            }
        }
    }
}
